[package]
name = "city-builder"
version = "0.1.0"
authors = ["Luca Fanselau <luca.fanselau@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.22.1"
log = "0.4.8"
simplelog = "0.7.6"
gfx-hal = "0.5"
# First we will just stick to vulkan so
gfx-backend-vulkan = "0.5"
arrayvec = "0.5.1"
shaderc = "0.6.2"
notify = "4.0.15"